version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es8net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: kibana8
    environment:
      - I18N_LOCALE=en-US
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
    ports:
      - "5601:5601"
    networks:
      - es8net
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: es8_01
    environment:
      - cluster.name=elasticsearchcluster1
      - node.name=es8_01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es8_01,es8_02
      - cluster.initial_master_nodes=es8_01,es8_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elasticsearch/data"
      # - es71plugins:"C:/Michael/DataExchange/DE8.0/EFK/DevEnv/elasticsearch/plugins"
    ports:
      - 9200:9200
    networks:
      - es8net
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: es8_02
    environment:
      - cluster.name=elasticsearchcluster1
      - node.name=es8_02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.seed_hosts=es8_01,es8_02
      - cluster.initial_master_nodes=es8_01,es8_02
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "./elasticsearch/data"
      # - es7data2:"C:/Michael/DataExchange/DE8.0/EFK/DevEnv/elasticsearch/data"
      # - es72plugins:"C:/Michael/DataExchange/DE8.0/EFK/DevEnv/elasticsearch/plugins"
      # - es7data2:/usr/share/elasticsearch/data
      # - es71plugins:/usr/share/elasticsearch/plugins
    networks:
      - es8net
# volumes:
#   es7data1:
#     driver: local
#   es7data2:
#     driver: local
#   es71plugins:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/plugins
#       o: bind
#   es72plugins:
#     driver: local
#     driver_opts:
#       type: none
#       device: $PWD/plugins
#       o: bind
networks:
  es8net:
    driver: bridge
